# Generated by Django 5.2.7 on 2026-03-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_asynkuser_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asynkuser',
            name='memberships',
        ),
    ]
