# Generated by Django 5.2.7 on 2026-02-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('mediaUrl', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('retryCount', models.IntegerField(default=0)),
                ('lastTriedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('roomName', models.CharField(max_length=50)),
                ('icon', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timeCreated'],
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
