# Generated by Django 5.2.7 on 2026-03-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommembership',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='roommembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomId',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
