# Generated by Django 5.2.7 on 2026-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0003_remove_roommembership_joined_at_roommembership_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomId',
            field=models.CharField(default='7447283212229537', max_length=16, primary_key=True, serialize=False),
        ),
    ]
