# Generated by Django 5.2.7 on 2026-03-10 01:38

import Messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0004_alter_room_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomId',
            field=models.CharField(default=Messaging.models.generate_id, max_length=16, primary_key=True, serialize=False),
        ),
    ]
