# Generated by Django 5.2.7 on 2026-05-03 01:40

import Messaging.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0007_alter_message_receiverid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.CharField(default=Messaging.models.generate_id, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Channel', max_length=25)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='Messaging.room')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Messaging.channel'),
        ),
    ]
