# Generated by Django 5.2.7 on 2026-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0008_remove_message_room_channel_message_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
